sudo: required
dist: trusty
language: ocaml
branches:
  only:
  - master
services:
- docker
env:
  global:
  - secure: Jpc4WOrSVTGgfXHOW4wbWU68BriVH/gMXJvfZtn2xiwDTzk49QnnzAVBYjPUJp4QoxAZ6kb3JGW/fBuSnMuEu+zxKLXAMftghLI3tQb6htPi7GkEeoQELTMaGNXe0lYzkQ/j+P+9c9Tu9uHJcHKdmaPjuMj6aOPs8YroQvq8bd4uGxks5zEc18LwlMRpZgirVO3awoeOXvp18WpPKt9thWebEYQFUMLIW65nsiWsAmzvbyvw8zCsfhg8lqANrzAQCEv+x9KFI0jKXi3Q00OijYYLpHaj18qns6Np1kvIcQ1ddsk3asP/Z1p6Msm+Iz5YjtF3eFlHM4riM6SVrKN/UcWNCA0/BJoOx+tVjOEyGtyud5q3wmBA1SQu2bhMbxYiMhQngWCl45J1Kb2vKWXr//2pXGRnY0MzxaVSfQEPlZv1aUwg1TyQ0J1nras0r24514OZw6WCnSmdpjzG9tnMunb41GrzToJdGwk5CHvGakfw4p6FWwloN1iJe9p47uC4vhcqF/5mNPU3dWUf00fyLcJSnro5yKc0ruA/YXkVr3/aSAmTZJ/dXRxOUoLoQaj59lH1QbajU1i0ev3HIWR6pP1tzHbqQVcmkIqfCRF/V1UshNaiL7KfZkjAutLacRj39JPvY3PXxmZl1hIPXnvfP5FQLBM4QT962qt7Fo3GQDs=
  - secure: aNofr/uJ1JArsQY7DP/gnFvBovc2oXUeCSSDo8AaExzGpKk6kB16X4uWDPyegAKlTnzlUgmUko8YMQS4XBH09zzqu8HhUKaO3JEtdeuaWKpj1p2jQW61/dAtLagS9xVIbL8Hc9/tgpjwADNIuKKhw2TbsQ05fSqaPgFZekRvpI2T86aL2PMfTN9JXfzOuO4MM+rPUFdcRYxi6myRUygWLfu3haSO11jFZCvKl0+TyOsMNFt7eoLrrczPA+yOpDNS4xNVzenx7OViWS1bOWO8Y8//wl6Nd/X9ff0dv3fkIavAiuXiz6RK756qVHB25n5FBw3WSleaJhJhxgpw4j2jjYOeGGjW92y47wD3x2qVvG4dROKmXHSnetBGzqB8jRHER8M8roF2ey3zr0UDdyeuFJaMntAe5wzVwW4mVqWSErJL25ujxwF6bp9fbrwSn7jdmBKDa5os0jl7ac7oPUZhFIs3PTvZ3Em4cowkvgfB73x9CztvFJM7qTFWEzckmp/fuYGYVS0tSJtUsLQgZuYDzcOx+9x195dObjowuza3XkJ+iDzxkYL50Zz46svg3FvINfUbzPY+B7a5FWUef642iMzXZoMkNpqCRTlxHY6oRpE6gePzHilCVuzf7dzMMQ71hg23/gvd/ONHqMTYCQnhpIjHchNna0uRfg7c4KDRTJc=
notifications:
  email:
  - tracker@easycrypt.info
before_install:
- docker pull easycryptpa/ec-doc-box
script:
- >-
  docker run -v $PWD:/home/ci/easycrypt-doc easycryptpa/ec-doc-box
  sh -c "git clone easycrypt-doc easycrypt-doc.dev && make -C easycrypt-doc.dev/refman"
after_success:
- >-
  curl --digest -u "${DAV_USER}:${DAV_PASSWORD}" -sT easycrypt-doc.dev/refman/refman.pdf
  https://www.easycrypt.info/documentation/refman.pdf
