#!/bin/bash

shopt -s extglob

rm -f tactics-examp0-*
easycrypt tactics-examp0.ec
../../common/procgoals tactics-examp0-+([0-9]).ec

rm -f tactics-examp1-*
easycrypt tactics-examp1.ec
../../common/procgoals tactics-examp1-+([0-9]).ec

rm -f tactics-examp2-*
easycrypt tactics-examp2.ec
../../common/procgoals tactics-examp2-+([0-9]).ec

cd tactics

cd generalize

rm -f 1-*
easycrypt 1.ec
../../../../common/procgoals 1-+([0-9]).ec

rm -f 2-*
easycrypt 2.ec
../../../../common/procgoals 2-+([0-9]).ec

cd .. # back to tactics directory

cd introduction

rm -f 1-*
easycrypt 1.ec
../../../../common/procgoals 1-+([0-9]).ec

rm -f 2-*
easycrypt 2.ec
../../../../common/procgoals 2-+([0-9]).ec

rm -f 3-*
easycrypt 3.ec
../../../../common/procgoals 3-+([0-9]).ec

rm -f 4-*
easycrypt 4.ec
../../../../common/procgoals 4-+([0-9]).ec

rm -f 5-*
easycrypt 5.ec
../../../../common/procgoals 5-+([0-9]).ec

rm -f 6-*
easycrypt 6.ec
../../../../common/procgoals 6-+([0-9]).ec

rm -f 7-*
easycrypt 7.ec
../../../../common/procgoals 7-+([0-9]).ec

cd .. # back to tactics directory
